// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQFrb776_x_RTcHvrC4pSFMttoOBeMJrU',
    appId: '1:835386941813:web:d61edb91f40fa37171333c',
    messagingSenderId: '835386941813',
    projectId: 'todo-fire-cb0c1',
    authDomain: 'todo-fire-cb0c1.firebaseapp.com',
    storageBucket: 'todo-fire-cb0c1.firebasestorage.app',
    measurementId: 'G-3R8LDS759E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-kcHMvUAHcZ9Y6BY2LsO1RGx3ZsntMiY',
    appId: '1:835386941813:android:a82cd0aa6d6a8c2a71333c',
    messagingSenderId: '835386941813',
    projectId: 'todo-fire-cb0c1',
    storageBucket: 'todo-fire-cb0c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0195IXczxlXCioYK9gk9R6vjJYMoAXEw',
    appId: '1:835386941813:ios:1820788db67cda0071333c',
    messagingSenderId: '835386941813',
    projectId: 'todo-fire-cb0c1',
    storageBucket: 'todo-fire-cb0c1.firebasestorage.app',
    iosClientId: '835386941813-a3fivf207s9co9rhip8g8rafdol2t11j.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFirebase',
  );

}